version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/node:12.18.1
    steps:
      - checkout
      - run:
          name: npm install
          command: npm i
      - run:
          name: test
          command: npm test

workflows:
    build-and-test:
      jobs:
        - build-and-test